name: "Split Software Evaluator"
author: "Sebastian Arrubia (github.com/splitio)"
description: "Evaluates your Split Feature Flags and set the evaluation treatments as output"
inputs:
  api-key: # Split api key
    description: "Split API key"
    required: true
    default: ""
  key: # user/evaluation key
    description: "Evaluation key"
    required: true
    default: ""
  splits:
    description: "Splits to be evaluated"
    required: true
    default: ""
outputs:
  result:
    description: "Evaluation results represented as JSON"
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "git-merge"
  color: "blue"
